$ANSIBLE_VAULT;1.1;AES256
36306265393561383535323963613335646530643137393365343838313338633235313664633165
6637353239353062396562633539363036303338323832390a386166383465653238363937343335
63363366366330643936653863313737653338623430386534663561663036383236323764383235
6335373135383666380a386135333165663236336136613536393063363832343336376136373664
39666534663836396638316364373633326539663761376664316561636366616163316534636135
61313932376661376362363830663234326336336632656265323262366264653931613762366237
63333037666361316162623336653734343837663366316261626266303438343438316538353635
37663934633363386132653134646234316665373432333566313366343034373735313938663762
6363
